export enum SmellType {
  LF = "Large File",
  LC = "Large Component",
  TP = "Too Many Props",
  IIC = "Inheritance Instead Of Composition",
  MB = "Multiple Booleans For State",
  FU = "Force Update",
  DOM = "Direct DOM Manipulation",
  JSX = "JSX Outside The Render Method",
  UC = "Uncontrolled Component",
  PIS = "Props In Initial State",
  ANY = "Any Type",
  NNA = "Many Non-Null Assertions",
  EIV = "Enum Implicit Values",
  CPP = "Children Props Pitfall",
  MUT = "Missing Union Types Abstraction",
}
